apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: amt-arrangor-alerts
  namespace: amt
  labels:
    team: amt
spec:
  groups:
    - name: amt-arrangor-alerts
      rules:
        - alert: applikasjon nede
          expr: kube_deployment_status_replicas_available{deployment="amt-arrangor"} == 0
          for: 2m
          annotations:
            summary: "App amt-arrangor er nede i prod"
            action: "`kubectl describe pod -l app={{ $labels.deployment}}` -> `kubectl logs -l app={{ $labels.deployment}}`"
          labels:
            namespace: amt
            severity: critical
        - alert: høy feilrate i logger
          expr: (100 * sum by (app, namespace) (rate(log_messages_errors{app="amt-arrangor",level="Error"}[3m])) / sum by (app, namespace) (rate(log_messages_total{app="amt-arrangor"}[3m]))) > 10
          for: 3m
          annotations:
            action: "Sjekk loggene til app amt-arrangor i namespace amt, for å se hvorfor det er så mye feil"
          labels:
            namespace: amt
            severity: warning
        - alert: feil logges
          expr: sum by(app, namespace) (increase(log_messages_errors{app="amt-arrangor",level="Error"}[5m])) > 0
          for: 5m
          annotations:
            action: "Sjekk loggene til app amt-arrangor i namespace amt, for å se hva som feiler"
          labels:
            namespace: amt
            severity: warning