kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-arrangor
  namespace: amt
  labels:
    team: amt
spec:
  image: {{image}}
  gcp:
    sqlInstances:
      - name: amt-arrangor
        type: POSTGRES_14
        databases:
          - name: amt-arrangor
            envVarPrefix: DB
        diskAutoresize: true
        highAvailability: false
        insights:
          enabled: true
  port: 8080
  ingresses:
    - https://amt-arrangor.intern.dev.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  startup:
    path: /internal/health/liveness
    initialDelay: 10
    failureThreshold: 30
    periodSeconds: 5
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 2048Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
  secureLogs:
    enabled: true
  kafka:
    pool: nav-dev
  leaderElection: true
  accessPolicy:
    inbound:
      rules:
        - application: amt-tiltak
        - application: amt-tiltaksarrangor-bff
    outbound:
      rules:
        - application: amt-enhetsregister
          namespace: amt
          cluster: dev-gcp
        - application: amt-altinn-acl
          namespace: amt
          cluster: dev-gcp
        - application: amt-tiltak
          namespace: amt
          cluster: dev-gcp
  env:
    - name: AMT_ENHETSREGISTER_URL
      value: http://amt-enhetsregister.amt.svc.cluster.local
    - name: AMT_ENHETSREGISTER_SCOPE
      value: api://dev-gcp.amt.amt-enhetsregister/.default
