kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-arrangor
  namespace: amt
  labels:
    team: amt
spec:
  image: {{image}}
  gcp:
    sqlInstances:
      - name: amt-arrangor-2
        type: POSTGRES_17
        tier: db-f1-micro
        databases:
          - name: amt-arrangor
            envVarPrefix: DB
        diskAutoresize: false
        highAvailability: false
        insights:
          enabled: true
  port: 8080
  ingresses:
    - https://amt-arrangor.intern.dev.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 30
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
  replicas:
    disableAutoScaling: true
    min: 1
    max: 1
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      memory: 1024Mi
  azure:
    application:
      enabled: true
  kafka:
    pool: nav-dev
  leaderElection: true
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: amt-tiltak
        - application: amt-tiltaksarrangor-bff
        - application: amt-aktivitetskort-publisher
        - application: amt-deltaker-bff
        - application: amt-deltaker
    outbound:
      rules:
        - application: amt-enhetsregister
          namespace: amt
          cluster: dev-gcp
        - application: amt-altinn-acl
          namespace: amt
          cluster: dev-gcp
        - application: amt-person-service
          namespace: amt
          cluster: dev-gcp
  env:
    - name: AMT_ENHETSREGISTER_URL
      value: http://amt-enhetsregister.amt.svc.cluster.local
    - name: AMT_ENHETSREGISTER_SCOPE
      value: api://dev-gcp.amt.amt-enhetsregister/.default

    - name: AMT_ALTINN_URL
      value: http://amt-altinn-acl.amt.svc.cluster.local
    - name: AMT_ALTINN_SCOPE
      value: api://dev-gcp.amt.amt-altinn-acl/.default

    - name: AMT_PERSON_URL
      value: http://amt-person-service.amt.svc.cluster.local
    - name: AMT_PERSON_SCOPE
      value: api://dev-gcp.amt.amt-person-service/.default


  observability:
      autoInstrumentation:
        enabled: true
        runtime: java
      logging:
        destinations:
          - id: elastic
          - id: loki
