CREATE SEQUENCE KAFKA_PRODUCER_RECORD_ID_SEQ;

CREATE TABLE KAFKA_PRODUCER_RECORD
(
    ID           BIGINT       NOT NULL PRIMARY KEY,
    TOPIC        VARCHAR(100) NOT NULL,
    KEY          BYTEA,
    VALUE        BYTEA,
    HEADERS_JSON TEXT,
    CREATED_AT   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE shedlock
(
    name       VARCHAR(128) PRIMARY KEY,
    lock_until TIMESTAMP(3),
    locked_at  TIMESTAMP(3),
    locked_by  VARCHAR(255)
);
